import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import Footer from '@/components/Foundations/Footer';

const outfit = Outfit({
  variable: "--fnt",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={outfit.variable}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
